household:
  filing_status: "married_filing_jointly"
  participants:
    - name: "Robert F. Gehrsitz"
      is_federal: true
      birth_date: "1965-02-25T00:00:00Z"
      hire_date: "1987-06-22T00:00:00Z"
      current_salary: "190779.00"
      high_3_salary: "190000.00"
      tsp_balance_traditional: "1966168.86"
      tsp_balance_roth: "0.00"
      tsp_contribution_percent: "0.128"
      ss_benefit_62: "2795.00"
      ss_benefit_fra: "4012.00"
      ss_benefit_70: "5000.00"
      fehb_premium_per_pay_period: "488.49"
      is_primary_fehb_holder: true
      survivor_benefit_election_percent: "0.00"
      sick_leave_hours: "1868.0"
    - name: "Dawn M. Gehrsitz"
      is_federal: true
      birth_date: "1963-07-31T00:00:00Z"
      hire_date: "1995-07-11T00:00:00Z"
      current_salary: "176620.00"
      high_3_salary: "164000.00"
      tsp_balance_traditional: "1525175.90"
      tsp_balance_roth: "0.00"
      tsp_contribution_percent: "0.153"
      ss_benefit_62: "2527.00"
      ss_benefit_fra: "3826.00"
      ss_benefit_70: "4860.00"
      fehb_premium_per_pay_period: "0.00"
      is_primary_fehb_holder: false
      survivor_benefit_election_percent: "0.00"
      sick_leave_hours: "1057.5"

global_assumptions:
  inflation_rate: "0.025"
  fehb_premium_inflation: "0.04"
  tsp_return_pre_retirement: "0.07"  # Conservative estimate for L 2030 funds
  tsp_return_post_retirement: "0.05"
  cola_general_rate: "0.025"
  projection_years: 25
  current_location:
    state: "PA"
    county: "Bucks"
    municipality: "Upper Makefield Township"

scenarios:
  - name: "Both Retire in 2025"
    participant_scenarios:
      "Robert F. Gehrsitz":
        participant_name: "Robert F. Gehrsitz"
        retirement_date: "2025-12-27T00:00:00Z"
        ss_start_age: 62
        tsp_withdrawal_strategy: "variable_percentage"
        tsp_withdrawal_rate: "0.01"
      "Dawn M. Gehrsitz":
        participant_name: "Dawn M. Gehrsitz"
        retirement_date: "2025-08-30T00:00:00Z"
        ss_start_age: 62
        tsp_withdrawal_strategy: "variable_percentage"
        tsp_withdrawal_rate: "0.01"

  - name: "Rob Retires at 62 - Feb 2027"
    participant_scenarios:
      "Robert F. Gehrsitz":
        participant_name: "Robert F. Gehrsitz"
        retirement_date: "2027-02-28T00:00:00Z"
        ss_start_age: 62
        tsp_withdrawal_strategy: "variable_percentage"
        tsp_withdrawal_rate: "0.01"
      "Dawn M. Gehrsitz":
        participant_name: "Dawn M. Gehrsitz"
        retirement_date: "2025-08-30T00:00:00Z"
        ss_start_age: 62
        tsp_withdrawal_strategy: "variable_percentage"
        tsp_withdrawal_rate: "0.01"

  - name: "Mortality Shock: Robert dies 2034"
    participant_scenarios:
      "Robert F. Gehrsitz":
        participant_name: "Robert F. Gehrsitz"
        retirement_date: "2025-12-27T00:00:00Z"
        ss_start_age: 62
        tsp_withdrawal_strategy: "variable_percentage"
        tsp_withdrawal_rate: "0.01"
      "Dawn M. Gehrsitz":
        participant_name: "Dawn M. Gehrsitz"
        retirement_date: "2025-08-30T00:00:00Z"
        ss_start_age: 62
        tsp_withdrawal_strategy: "variable_percentage"
        tsp_withdrawal_rate: "0.01"
    mortality:
      participants:
        "Robert F. Gehrsitz":
          death_date: "2034-06-30T00:00:00Z"
      assumptions:
        survivor_spending_factor: "0.90"
        tsp_spousal_transfer: "merge"
        filing_status_switch: "next_year"
