# FERS Retirement Calculator - Comprehensive Configuration
# This configuration includes all parameters with annotated defaults
# to eliminate hard-coded values throughout the application

personal_details:
  robert:
    name: "Robert F. Gehrsitz"
    birth_date: "1965-02-25T00:00:00Z"
    hire_date: "1987-06-22T00:00:00Z"  # Service Computation Date (SCD Leave)
    current_salary: "190779.00"
    high_3_salary: "190000.00"  # Corrected from documents
    tsp_balance_traditional: "1966168.86"
    tsp_balance_roth: "0.00"
    tsp_contribution_percent: "0.128"  # $24,501.54 / $190,779.00
    ss_benefit_62: "2795.00"  # Monthly benefit at age 62
    ss_benefit_fra: "4012.00"  # Monthly benefit at FRA (67)
    ss_benefit_70: "5000.00"  # Monthly benefit at age 70
    fehb_premium_monthly: "488.49"  # $488.49 per pay period (will be multiplied by 26 pay periods)
    survivor_benefit_election_percent: "0.00"
    
    # Individual TSP allocation (optional - uses default if not specified)
    # Robert uses L 2030 fund which is aggressive growth
    tsp_allocation:
      c_fund: "0.55"  # 55% Large Cap Stocks
      s_fund: "0.25"  # 25% Small Cap Stocks  
      i_fund: "0.15"  # 15% International Stocks
      f_fund: "0.05"  # 5% Fixed Income
      g_fund: "0.00"  # 0% Government Securities
    
  dawn:
    name: "Dawn M. Gehrsitz"
    birth_date: "1963-07-31T00:00:00Z"
    hire_date: "1995-07-11T00:00:00Z"  # Service Computation Date (SCD Leave)
    current_salary: "176620.00"
    high_3_salary: "164000.00"  # Corrected from documents
    tsp_balance_traditional: "1525175.90"
    tsp_balance_roth: "0.00"
    tsp_contribution_percent: "0.153"  # $26,962.00 / $176,620.00
    ss_benefit_62: "2527.00"  # Monthly benefit at age 62
    ss_benefit_fra: "3826.00"  # Monthly benefit at FRA (67)
    ss_benefit_70: "4860.00"  # Monthly benefit at age 70
    fehb_premium_monthly: "0.00"  # Dawn has FSA-HC instead of FEHB ($105.76 per pay period)
    survivor_benefit_election_percent: "0.00"
    
    # Dawn switching from L Income to L 2030 (100% future allocation)
    tsp_allocation:
      c_fund: "0.55"  # 55% Large Cap Stocks
      s_fund: "0.25"  # 25% Small Cap Stocks
      i_fund: "0.15"  # 15% International Stocks
      f_fund: "0.05"  # 5% Fixed Income
      g_fund: "0.00"  # 0% Government Securities

global_assumptions:
  inflation_rate: "0.025"
  fehb_premium_inflation: "0.04"
  tsp_return_pre_retirement: "0.07"  # Conservative estimate for L 2030 funds
  tsp_return_post_retirement: "0.05"
  cola_general_rate: "0.025"
  projection_years: 25
  current_location:
    state: "PA"
    county: "Bucks"
    municipality: "Upper Makefield Township"

  # Monte Carlo Simulation Settings
  monte_carlo_settings:
    # Variability parameters for statistical generation (standard deviations)
    tsp_return_variability: "0.15"      # 15% std dev - typical for stock market variability
    inflation_variability: "0.02"       # 2% std dev - based on CPI historical variation
    cola_variability: "0.02"            # 2% std dev - Social Security COLA variation
    fehb_variability: "0.05"            # 5% std dev - health insurance premium increases

    # Income validation limits
    max_reasonable_income: "50000000"    # $50M annual cap to prevent calculation errors

    # Default TSP asset allocation (used when individual allocation not specified)
    # Based on typical balanced portfolio for federal employees near retirement
    default_tsp_allocation:
      c_fund: "0.60"  # 60% - C Fund (Large Cap Stock Index, tracks S&P 500)
      s_fund: "0.20"  # 20% - S Fund (Small Cap Stock Index, tracks Russell 2000)
      i_fund: "0.10"  # 10% - I Fund (International Stock Index, tracks MSCI World ex-US)
      f_fund: "0.10"  # 10% - F Fund (Fixed Income Index, tracks Bloomberg US Aggregate)
      g_fund: "0.00"  # 0% - G Fund (Government Securities, guaranteed return)

  # Federal Rules and Limits (updated annually by IRS/SSA)
  federal_rules:
    # Social Security taxation thresholds - 2025 values
    # Source: IRS Publication 915 and Social Security Administration
    social_security_tax_thresholds:
      married_filing_jointly:
        threshold_1: "32000"  # 50% of SS benefits may be taxable above this income
        threshold_2: "44000"  # 85% of SS benefits may be taxable above this income
      single:
        threshold_1: "25000"  # 50% of SS benefits may be taxable above this income  
        threshold_2: "34000"  # 85% of SS benefits may be taxable above this income

    # Social Security benefit calculation rules
    # Source: Social Security Administration actuarial tables
    social_security_rules:
      early_retirement_reduction:
        first_36_months_rate: "0.0055556"    # 5/9 of 1% per month (6.67% annually)
        additional_months_rate: "0.0041667"  # 5/12 of 1% per month (5% annually)
      delayed_retirement_credit: "0.0066667" # 2/3 of 1% per month (8% annually)

    # FERS program rules
    # Source: OPM FERS Handbook and current regulations
    fers_rules:
      tsp_matching_rate: "0.05"        # 5% maximum agency matching contribution
      tsp_matching_threshold: "0.05"   # 5% employee contribution required for full match

  # TSP Statistical Models - calculated from historical data
  # Source: TSP.gov historical performance data, updated annually
  tsp_statistical_models:
    c_fund:
      mean: "0.1125"                    # 11.25% - historical mean return (1988-2024)
      standard_dev: "0.1744"           # 17.44% - historical standard deviation
      data_source: "TSP.gov 1988-2024"
      last_updated: "2025-01-01"
    
    s_fund:
      mean: "0.1117"                    # 11.17% - historical mean return (1988-2024)
      standard_dev: "0.1933"           # 19.33% - historical standard deviation
      data_source: "TSP.gov 1988-2024"
      last_updated: "2025-01-01"
    
    i_fund:
      mean: "0.0634"                    # 6.34% - historical mean return (1988-2024)
      standard_dev: "0.1863"           # 18.63% - historical standard deviation
      data_source: "TSP.gov 1988-2024"
      last_updated: "2025-01-01"
    
    f_fund:
      mean: "0.0532"                    # 5.32% - historical mean return (1988-2024)
      standard_dev: "0.0565"           # 5.65% - historical standard deviation
      data_source: "TSP.gov 1988-2024"
      last_updated: "2025-01-01"
    
    g_fund:
      mean: "0.0493"                    # 4.93% - historical mean return (1988-2024)
      standard_dev: "0.0165"           # 1.65% - historical standard deviation (very stable)
      data_source: "TSP.gov 1988-2024"
      last_updated: "2025-01-01"

scenarios:
  - name: "Both Retire in 2025"
    robert:
      employee_name: "robert"
      retirement_date: "2025-12-27T00:00:00Z"
      ss_start_age: 62
      tsp_withdrawal_strategy: "variable_percentage"
      tsp_withdrawal_rate: "0.04"  # 1% withdrawal rate (conservative)
    dawn:
      employee_name: "dawn"
      retirement_date: "2025-08-30T00:00:00Z"
      ss_start_age: 62
      tsp_withdrawal_strategy: "variable_percentage"
      tsp_withdrawal_rate: "0.04"  # 1% withdrawal rate (conservative)
      
  - name: "Rob Retires at 62 - Feb 2027"
    robert:
      employee_name: "robert"
      retirement_date: "2027-02-28T00:00:00Z"
      ss_start_age: 62
      tsp_withdrawal_strategy: "variable_percentage"
      tsp_withdrawal_rate: "0.04"  # 1% withdrawal rate (conservative)
    dawn:
      employee_name: "dawn"
      retirement_date: "2025-08-30T00:00:00Z"
      ss_start_age: 62
      tsp_withdrawal_strategy: "variable_percentage"
      tsp_withdrawal_rate: "0.04"  # 1% withdrawal rate (conservative)