personal_details:
    dawn:
        name: Dawn M. Gehrsitz
        birth_date: 1963-07-31T00:00:00Z
        hire_date: 1988-07-10T00:00:00Z
        current_salary: "176620"
        high_3_salary: "176620"
        tsp_balance_traditional: "1525175.90"
        tsp_balance_roth: "0"
        tsp_contribution_percent: "0.15"
        ss_benefit_fra: "3826"
        ss_benefit_62: "2527"
        ss_benefit_70: "4860"
        fehb_premium_monthly: "0"
        survivor_benefit_election_percent: "0"
        # Optional context fields (not used in calculations)
        pay_plan_grade: "NM-04"
        ssn_last4: "0570"
    robert:
        name: Robert F. Gehrsitz
        birth_date: 1965-02-25T00:00:00Z
        hire_date: 1985-03-20T00:00:00Z
        current_salary: "190779"
        high_3_salary: "190779"
        tsp_balance_traditional: "1966168.86"
        tsp_balance_roth: "0"
        tsp_contribution_percent: "0.15"
        ss_benefit_fra: "4012"
        ss_benefit_62: "2795"
        ss_benefit_70: "5000"
        fehb_premium_monthly: "875"
        survivor_benefit_election_percent: "0"
        # Optional context fields (not used in calculations)
        pay_plan_grade: "NM-05"
        ssn_last4: "5061"

global_assumptions:
    inflation_rate: "0.025"
    fehb_premium_inflation: "0.065"
    tsp_return_pre_retirement: "0.055"
    tsp_return_post_retirement: "0.045"
    cola_general_rate: "0.025"
    projection_years: 25
    current_location:
        state: Pennsylvania
        county: Bucks
        municipality: Upper Makefield Township

scenarios:
    - name: Early Retirement 2025
      robert:
        employee_name: robert
        retirement_date: 2025-12-31T00:00:00Z
        ss_start_age: 62
        tsp_withdrawal_strategy: 4_percent_rule
      dawn:
        employee_name: dawn
        retirement_date: 2025-12-31T00:00:00Z
        ss_start_age: 62
        tsp_withdrawal_strategy: 4_percent_rule
    - name: Delayed Retirement 2028
      robert:
        employee_name: robert
        retirement_date: 2028-12-31T00:00:00Z
        ss_start_age: 67
        tsp_withdrawal_strategy: need_based
        tsp_withdrawal_target_monthly: "3000"
      dawn:
        employee_name: dawn
        retirement_date: 2028-12-31T00:00:00Z
        ss_start_age: 62
        tsp_withdrawal_strategy: 4_percent_rule
    - name: Full Retirement Age 2032
      robert:
        employee_name: robert
        retirement_date: 2032-02-25T00:00:00Z  # Robert's 67th birthday
        ss_start_age: 67
        tsp_withdrawal_strategy: need_based
        tsp_withdrawal_target_monthly: "2500"
      dawn:
        employee_name: dawn
        retirement_date: 2030-07-31T00:00:00Z  # Dawn's 67th birthday
        ss_start_age: 67
        tsp_withdrawal_strategy: need_based
        tsp_withdrawal_target_monthly: "2500"
